### ISSUE TITLE
License

### ISSUE THREAD

**Issue by steven851007** [thybag/JavaScript-Ical-Parser#1]
Could you specify the License for this code? Because I'm not sure could I use the code in my project. Thx

**Comment by thybag** [comment]
Ah, sorry, I must have forgoten to add a licence to the readme.

I normally just go with the MIT licence, although I'm happy to re-licence the script under an alternative one if the MIT licence is restricting you from using the code in anyway. Currently its mostly just a proof of concept so you may have to make some alterations in order to ensure correct handling of recurring events/todo's etc.

Thanks,
Carl

**Comment by steven851007** [comment]
MIT license is good! Could you include it into the readme? 
Thank you Carl!

**Comment by thybag** [comment]
Hello,

Just updated the readme to include the licence :) 

Thanks,
Carl
